import json
from crunchyroll_api import CrunchyrollClient

SERIES_ID = "GRMG8ZQZR"

client = CrunchyrollClient(locale="en-US")
client.login_anonymous()

seasons = client.get_seasons(SERIES_ID)

episode_map = {}

for season in seasons:
    episodes = client.get_episodes(season.id)

    for episode in episodes:
        raw = episode.raw or {}

        episode_number = (
            raw.get("episode_number")
            or raw.get("episode")
            or getattr(episode, "episode_number", None)
        )

        if episode_number is None:
            continue

        try:
            number = int(float(str(episode_number)))
        except (ValueError, TypeError):
            continue

        episode_map[str(number)] = (
            f"https://www.crunchyroll.com/watch/{episode.id}"
        )

output = {
    "series": "One Piece",
    "seriesId": SERIES_ID,
    "source": "Generated by GitHub Actions",
    "mappedCount": len(episode_map),
    "episodes": dict(
        sorted(
            episode_map.items(),
            key=lambda item: int(item[0])
        )
    ),
}

with open("crunchyroll-map.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"Mapped {len(episode_map)} One Piece episodes.")
